# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionStatusDescription',
            fields=[
                ('execution_status_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('execution_desc', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'ars_execution_status_description',
                'ordering': ('execution_status_id',),
            },
        ),
    ]
