# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestScripData',
            fields=[
                ('test_script_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('test_script_name', models.CharField(max_length=254)),
                ('test_script_source_file', models.TextField(null=True)),
            ],
            options={
                'db_table': 'ars_test_script_data',
                'ordering': ('test_script_id',),
            },
        ),
    ]
