# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TestScriptData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScripAsset',
            fields=[
                ('test_script_asset_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('test_script_asset_name', models.CharField(max_length=254)),
                ('test_script_asset_extension_file_type', models.CharField(max_length=254)),
                ('test_script_asset_source_file', models.FileField(upload_to='')),
                ('test_script_id', models.ForeignKey(db_column='test_script_id', on_delete=django.db.models.deletion.CASCADE, to='TestScriptData.TestScripData')),
            ],
            options={
                'db_table': 'ars_test_script_asset',
                'ordering': ('test_script_asset_id',),
            },
            managers=[
                ('TestScriptDataManagerObject', django.db.models.manager.Manager()),
            ],
        ),
    ]
