# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ExecutionStatusDescription', '0001_initial'),
        ('SuiteStatistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStatistic',
            fields=[
                ('test_statistic_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('test_script_name', models.TextField()),
                ('execution_time', models.DurationField(default=None, null=True)),
                ('execution_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('test_statistic_error_message', models.TextField(blank=True, default=None, null=True)),
                ('execution_status', models.ForeignKey(db_column='execution_status', on_delete=django.db.models.deletion.CASCADE, to='ExecutionStatusDescription.ExecutionStatusDescription')),
                ('suites_statistic_id', models.ForeignKey(db_column='suites_statistic_id', on_delete=django.db.models.deletion.CASCADE, to='SuiteStatistic.SuitesStatistic')),
            ],
            options={
                'db_table': 'ars_test_statistic',
                'ordering': ('test_statistic_id',),
            },
        ),
    ]
