-- MySQL Script generated by MySQL Workbench
-- Fri May 19 20:35:17 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ars
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ars
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ars` DEFAULT CHARACTER SET utf8 ;
USE `ars` ;

-- -----------------------------------------------------
-- Table `ars`.`ars_suites_statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ars`.`ars_suites_statistics` (
  `suites_statistics_id` INT NOT NULL AUTO_INCREMENT,
  `suites_module` VARCHAR(45) NOT NULL,
  `suites_run_date` DATETIME NOT NULL,
  `suites_execution_status` TINYINT(1) NOT NULL,
  `suites_total_test` INT(255) NOT NULL,
  `suites_total_passed` INT(255) NOT NULL,
  `suites_total_failed` INT(255) NOT NULL,
  `suites_total_errors` INT(255) NOT NULL,
  `suites_execution_time` DATETIME NOT NULL,
  `suites_execution_start_time` DATETIME NOT NULL,
  `suites_execution_end_time` DATETIME NOT NULL,
  PRIMARY KEY (`suites_statistics_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ars`.`ars_test_scrips_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ars`.`ars_test_scrips_data` (
  `test_script_id` INT NOT NULL AUTO_INCREMENT,
  `test_script_name` VARCHAR(255) NOT NULL,
  `test_script_data` LONGTEXT NOT NULL,
  `test_script_created_date` DATETIME NOT NULL,
  `test_script_modify_date` DATETIME NOT NULL,
  PRIMARY KEY (`test_script_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ars`.`ars_test_statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ars`.`ars_test_statistics` (
  `test_statistics_id` INT NOT NULL AUTO_INCREMENT,
  `suites_statistics_id` INT NOT NULL,
  `test_script_id` INT NOT NULL,
  `test_execution_status` TINYINT(1) NOT NULL,
  `test_failed_message` LONGTEXT NOT NULL,
  `test_execution_time` DATETIME NOT NULL,
  `test_execution_start_time` DATETIME NOT NULL,
  `test_execution_end_time` DATETIME NOT NULL,
  PRIMARY KEY (`test_statistics_id`),
  INDEX `fk_ars_test_statistics_ars_suites_statistics_idx` (`suites_statistics_id` ASC),
  INDEX `fk_ars_test_statistics_ars_test_scrips_data1_idx` (`test_script_id` ASC),
  CONSTRAINT `fk_ars_test_statistics_ars_suites_statistics`
    FOREIGN KEY (`suites_statistics_id`)
    REFERENCES `ars`.`ars_suites_statistics` (`suites_statistics_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ars_test_statistics_ars_test_scrips_data1`
    FOREIGN KEY (`test_script_id`)
    REFERENCES `ars`.`ars_test_scrips_data` (`test_script_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ars`.`ars_test_assets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ars`.`ars_test_assets` (
  `test_assets_id` INT NOT NULL,
  `test_statistics_id` INT NOT NULL,
  `test_assets_file_name` VARCHAR(45) NULL,
  `test_assets_raw_data` LONGBLOB NULL,
  PRIMARY KEY (`test_assets_id`),
  INDEX `fk_ars_test_assets_ars_test_statistics1_idx` (`test_statistics_id` ASC),
  CONSTRAINT `fk_ars_test_assets_ars_test_statistics1`
    FOREIGN KEY (`test_statistics_id`)
    REFERENCES `ars`.`ars_test_statistics` (`test_statistics_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
